package:
  name: wsdt
  version: "0.1"

source:
  git_url: ../
  git_tag: HEAD

build:
  number: 6
  string: py27_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - python 2.7*
    - setuptools

  run:
    - python 2.7*
    - numpy
    - vigra >=1.11
    - networkx

test:
  requires:
    - nose
    - numpy-allocation-tracking # This package can be found in the ilastik channel

  imports:
    - wsdt
  
about:
  summary: Implementation of a distance-transform-based watershed algorithm
